repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: run-tests
        name: run-tests
        description: This hook runs my tests.
        entry: python test_entrypoint.py
        language: python
